[package]
name = "gospel"
version = "0.1.0"
edition = "2024"

[dependencies]
encoding_rs = "0.8.35"
serde_json = "1.0.142"
serde = { version = "1.0.142", features = ["derive"] }
clap = { version = "4.5.43", features = ["derive"] }
indicatif = "0.18.0"
